#!/usr/bin/env bash
# One-time (re-runnable) setup: secrets -> certs -> MQTT users.
set -euo pipefail
cd "$(dirname "$0")/.."
command -v openssl >/dev/null || { echo "openssl is required"; exit 1; }

rand() { openssl rand -hex 24; }
if [ ! -f .env ]; then
  echo ">> Generating .env with random secrets"
  {
    echo "# Generated by scripts/setup.sh. NEVER commit this file."
    echo "POSTGRES_USER=smartsecure"
    echo "POSTGRES_DB=smartsecure"
    echo "POSTGRES_PASSWORD=$(rand)"
    echo "JWT_SECRET=$(rand)"
    echo "JWT_ALGORITHM=HS256"
    echo "JWT_EXPIRE_MINUTES=60"
    echo "API_USERS=admin:$(rand)"
    echo "API_DOCS_ENABLED=true   # dev only; NEVER true in production"
    echo "DASHBOARD_PORT=8080"
    echo "STORAGE_KEY=$(rand)"
    for s in ADMIN API SIMULATORS VISION CYBER ENGINE; do echo "MQTT_PASSWORD_$s=$(rand)"; done
  } > .env
  chmod 600 .env
else
  # Windows editors often save .env as CRLF, which makes `set -a; . ./.env`
  # deliver values with a trailing \r to Docker/OpenSSL. Normalize and never
  # touch the .env if any of the required keys are missing (someone edited it).
  sed -i 's/\r$//' .env
  if ! grep -q '^STORAGE_KEY=' .env; then echo "STORAGE_KEY=$(rand)" >> .env; fi
  echo ">> .env already exists, keeping it"
fi

./scripts/gen-certs.sh
./scripts/gen-mqtt-passwd.sh
echo ">> Done. Next: make up && make smoke"
