#!/usr/bin/env bash
# One-time (re-runnable) setup: secrets -> certs -> MQTT users.
set -euo pipefail
cd "$(dirname "$0")/.."
command -v openssl >/dev/null || { echo "openssl is required"; exit 1; }

rand() { openssl rand -hex 24; }
if [ ! -f .env ]; then
  echo ">> Generating .env with random secrets"
  {
    echo "# Generated by scripts/setup.sh. NEVER commit this file."
    echo "POSTGRES_USER=smartsecure"
    echo "POSTGRES_DB=smartsecure"
    echo "POSTGRES_PASSWORD=$(rand)"
    echo "JWT_SECRET=$(rand)"
    echo "JWT_ALGORITHM=HS256"
    echo "JWT_EXPIRE_MINUTES=60"
    echo "API_USERS=admin:$(rand)"
    echo "API_DOCS_ENABLED=true   # dev only; NEVER true in production"
    echo "DASHBOARD_PORT=8080"
    for s in ADMIN API SIMULATORS VISION CYBER ENGINE; do echo "MQTT_PASSWORD_$s=$(rand)"; done
  } > .env
  chmod 600 .env
else
  echo ">> .env already exists, keeping it"
fi

./scripts/gen-certs.sh
./scripts/gen-mqtt-passwd.sh
echo ">> Done. Next: make up && make smoke"
